// <auto-generated />
using Car_license_plate__CLP__DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car_license_plate__CLP__DB.Migrations
{
    [DbContext(typeof(CLP))]
    [Migration("20230927175815_o1")]
    partial class o1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Car_license_plate__CLP__DB.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 5,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 5,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 5,
                            Name = "Fiat"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 5,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 11,
                            Name = "Škoda"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            Name = "Jeep"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 13,
                            Name = "Maseratti"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 14,
                            Name = "Koenigsegg"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 13,
                            Name = "Lamborghini"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 11,
                            Name = "McLaren"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 2,
                            Name = "Delorean"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 5,
                            Name = "Siat"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 7,
                            Name = "Nisan"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 5,
                            Name = "Opel"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 2,
                            Name = "Lincoln"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 7,
                            Name = "Suzuki"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 4,
                            Name = "Volvo"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 15,
                            Name = "Scania"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 16,
                            Name = "DAF"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 2,
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 5,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 17,
                            Name = "Cupra"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 7,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 7,
                            Name = "Subaru"
                        });
                });

            modelBuilder.Entity("Car_license_plate__CLP__DB.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("DriveId")
                        .HasColumnType("int");

                    b.Property<bool>("IsWanted")
                        .HasColumnType("bit");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Mileage")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("DriveId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            ColorId = 10,
                            DriveId = 3,
                            IsWanted = false,
                            LicensePlate = "BK6969TR",
                            Mileage = 0.0,
                            Model = "RS 7",
                            Owner = "ANDRII HRITSIUK",
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            ColorId = 8,
                            DriveId = 2,
                            IsWanted = false,
                            LicensePlate = "BK1986CH",
                            Mileage = 1986.04,
                            Model = "220",
                            Owner = "SVIATOSLAV SAPACH",
                            Year = 2015
                        });
                });

            modelBuilder.Entity("Car_license_plate__CLP__DB.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lime"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Purple"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 11,
                            Name = "White"
                        });
                });

            modelBuilder.Entity("Car_license_plate__CLP__DB.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 2,
                            Name = "USA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 5,
                            Name = "German"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 8,
                            Name = "China"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 11,
                            Name = "UK"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Czech"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Spain"
                        });
                });

            modelBuilder.Entity("Car_license_plate__CLP__DB.Drive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drives");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Back"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Front"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Full"
                        });
                });

            modelBuilder.Entity("Car_license_plate__CLP__DB.Brand", b =>
                {
                    b.HasOne("Car_license_plate__CLP__DB.Country", "Country")
                        .WithMany("Brands")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Car_license_plate__CLP__DB.Car", b =>
                {
                    b.HasOne("Car_license_plate__CLP__DB.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_license_plate__CLP__DB.Color", "Color")
                        .WithMany("Cars")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Car_license_plate__CLP__DB.Drive", "Drive")
                        .WithMany("Cars")
                        .HasForeignKey("DriveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Drive");
                });

            modelBuilder.Entity("Car_license_plate__CLP__DB.Brand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Car_license_plate__CLP__DB.Color", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Car_license_plate__CLP__DB.Country", b =>
                {
                    b.Navigation("Brands");
                });

            modelBuilder.Entity("Car_license_plate__CLP__DB.Drive", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
